spring:
  datasource:
    #    TODO: move credentials to env variables - respectively decouple db from a
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console


  liquibase.change-log:
    classpath:db/changelog/changelog-master.xml