name: Call a reusable workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-test:
    uses: ExplodingSalad/SampleCICD/.github/workflows/build-and-test.yml@master
  # Creates  GitHub release, builds and pushes a docker image
  release:
    if: github.event_name == 'push'
    uses: ExplodingSalad/SampleCICD/.github/workflows/release.yml@master
