name: Call a reusable workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-test:
    uses: ExplodingSalad/SampleCICD/.github/workflows/build-and-test.yml@master
  release:
    uses: ExplodingSalad/SampleCICD/.github/workflows/release.yml@master
