name: Call a reusable workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs: 
  build-and-test:
    # Importing a reusable workflow from another repository and branch
    # uses: organization/repo/.github/workflows/build-test-deploy.yml@main
    uses: ExplodingSalad/SampleCICD/.github/workflows/github-workflow.yml@master
