name: Call a reusable workflow

on:
#  pull_request:
#    branches:
#      - master
  push:
    branches:
      - master

jobs:
  template-pipeline:
    uses: ExplodingSalad/SampleCICD/.github/workflows/github-actions-template.yml@master
    with:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
